### ISSUE TITLE
Allow for configurable test profiles

### ISSUE THREAD

**Issue by wagoodman** [wagoodman/canopy#8]
This will be enabled by https://github.com/anchore/fangs/pull/51 with the `--profile` flag, so you can keep:

```yaml
#.canopy.yaml

profiles:
 unit:
   # some test flags
  integration:
    # some other test flags

```

```
canopy --profile unit ./...
```
